### ISSUE TITLE
Build error with flatpak configuration

### ISSUE THREAD

**Issue by sudden6** [flathub/io.github.qtox.qTox#13]
In https://github.com/qTox/qTox/pull/5999 I try to minimize the differences between the flathub builds and our CI and nightly builds, but I can not build the TCL dependency which is needed for sqlcipher. Is there some special setup on flathub to make this work?

The relevant build output is approximately here: https://travis-ci.org/github/qTox/qTox/jobs/662451860#L2185

The whole build is executed in a `debian:stretch-slim` docker container.

ping @dgcampea because you seem to have authored the changes for this flathub repo.

**Comment by dgcampea** [comment]
Fedora 31 here, it builds fine with `flatpak-builder 1.0.9`.
Comparing the manifest file, I don't see any changes that would impact TCL or sqlcipher.
KDE Sdk info: 
```
$ flatpak info org.kde.Sdk//5.12

KDE Software Development Kit - Tools and headers for developing applications
using the KDE application platform

          ID: org.kde.Sdk
         Ref: runtime/org.kde.Sdk/x86_64/5.12
        Arch: x86_64
      Branch: 5.12
     License: GPL-2.0+
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 2.4 GB

      Commit: af77ec99eb9e255d9adf5118a8585354e9b208c6d724df6dab716db33774c95a
      Parent: 11304b93dcb1ed4aa88405dd5a41524d92ab33c7cd66d40533fda77842d88678
     Subject: Update kf5 to last version, also plasma to 5.18 which is LTS (213e641b)
        Date: 2020-03-14 01:26:03 +0000
```

Slightly off-topic, what is `snorenotify` dependency used for? (https://github.com/qTox/qTox/blob/3b3b109b9fe8015eb8e3dcfe2ba7b5bffaa4af10/flatpak/io.github.qtox.qTox.json#L82)

**Comment by sudden6** [comment]
Thx for the answer, I just figured out that I forgot to remove the global build flags you also removed in your commit.

`snorenotify` is used for desktop notifications, but they also have to be enabled by a cmake switch: `-DDESKTOP_NOTIFICATIONS=True`
